name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  http: ^1.2.2
  provider: ^6.1.2
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/android_icon.png" # Path to your Android icon